FROM bitnami/tomcat:9.0

ENV TOMCAT_PASSWORD=passer

ENV TOMCAT_USERNAME=seckngor

#docker build -t tomcat:9.0 .
#Si la commande ne marche pas essaie ceci : docker logout ou docker pull hello-world ouecore verifier dockerDesktop
#docker run -p 8081:8080 -d tomcat:9.0
#docker exec -it container_id /bin/bash
#ls opt/bitnami/apache-tomcat/conf/
#http://localhost:8081/projects/angularProjects/gestionusers/allusers.php