version: '3'

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      - TOMCAT_USERNAME=seckngor
      - TOMCAT_PASSWORD=passer
    volumes:
      - bitnami-data:/bitnami
volumes:
  bitnami-data:
    driver: local

#docker compose up -d