FROM bitnami/tomcat:9.0

COPY ./DeploiementIage.war /opt/bitnami/tomcat/webapps/

COPY ./DemoDeploiementm1rsi.war /opt/bitnami/tomcat/webapps/
#docker build -t tomcat:9.0 .
#Si la commande ne marche pas essaie ceci : docker logout ou docker pull hello-world ouecore verifier dockerDesktop
#docker run -p 8081:8080 -d tomcat:9.0
#docker exec -it container_id /bin/bash
#ls opt/bitnami/apache-tomcat/conf/
#http://localhost:8082/DemoDeploiementm1rsi
#http://localhost:8082/DeploiementIage